### ISSUE TITLE
Cannot flash with a Mac

### ISSUE THREAD

**Issue by gabemorris12** [JetBrains/intellij-micropython#290]
I'm not sure if this project is still alive, but I thought that everything was working except for the REPL console. I haven't been able to test with Windows lately, but I get this error:

```
Connecting to /dev/cu.usbmodem2101
Uploading files: 0% (0/1)
/Users/gabemorris/Python/pico_concepts/Flashing Light/main.py -> Flashing Light/main.py
b'rw '
Traceback (most recent call last):
  File "/Users/gabemorris/Library/Application Support/JetBrains/PyCharm2024.1/plugins/intellij-micropython/scripts/microupload.py", line 139, in <module>
    main(sys.argv[1:])
  File "/Users/gabemorris/Library/Application Support/JetBrains/PyCharm2024.1/plugins/intellij-micropython/scripts/microupload.py", line 77, in main
    make_dirs(files, remote_dir, created_cache)
  File "/Users/gabemorris/Library/Application Support/JetBrains/PyCharm2024.1/plugins/intellij-micropython/scripts/microupload.py", line 97, in make_dirs
    files.mkdir(posix_path)
  File "/Users/gabemorris/pico_env/lib/python3.12/site-packages/ampy/files.py", line 190, in mkdir
    self._pyboard.enter_raw_repl()
  File "/Users/gabemorris/pico_env/lib/python3.12/site-packages/ampy/pyboard.py", line 192, in enter_raw_repl
    raise PyboardError('could not enter raw repl')
ampy.pyboard.PyboardError: could not enter raw repl
```

I even tried the plugin posted in #289, but that results in the same error. Is this plugin supported for Apple Silicon?

**Comment by Luky557** [comment]
@gabemorris12 Try now works for me on a Mac. Beware, you might get "Keyboard interrupt" if you select open REPL on success in the REPL configuration, just press the reset button on your device and it should work from there.
